name: Actions Workflow
on: [push, pull_request]
defaults:
  run:
    shell: pwsh
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # get the docker container
      - name: Startup the container
        run: docker run -p 8834:8834 --hostname nessus --name nessus -d sometheycallme/docker-nessus:latest

      # setup nessus
      - name: Sleep to give nessus time to startup
        run: Start-Sleep 20
      - name: Write nessus license
        run: $env:NLICENSE | Set-Content -Path /tmp/nessus.license
        env:
          NLICENSE: ${{secrets.LICENSE}}

    - name: Set required PowerShell modules
      id: psmodulecache
      uses: potatoqualitee/psmodulecache@v1
      with:
        modules-to-cache: PSFramework, Pester, dbatools
    - name: Setup PowerShell module cache
      id: cacher
      uses: actions/cache@v2
      with:
          path: ${{ steps.psmodulecache.outputs.modulepath }}
          key: ${{ steps.psmodulecache.outputs.keygen }}
    - name: Install required PowerShell modules
      if: steps.cacher.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module ${{ steps.psmodulecache.outputs.needed }} -ErrorAction Stop

      - name: Import tentools and test connect to the container
        run: |
          Import-Module ./tentools.psd1
          $splat = @{
            ComputerName = "localhost"
            Port = 8834
          }
          Connect-TenService @splat

          # notes for presentation:
          # go check out azurite for reiteration: https://github.com/potatoqualitee/azuright