on: [push]

jobs:
  run-on-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create variables for module cacher
      id: psmodulecache
      uses: potatoqualitee/psmodulecache@v4
      with:
        modules-to-cache: PSFramework, Pester, dbatools:1.0.0
    - name: Show that the Action works
      shell: pwsh
      run: |
          Get-Module -Name PSFramework, Pester, dbatools -ListAvailable | Select Path